### ISSUE TITLE
generazione link

### ISSUE THREAD

**Issue by ragnar-homekit** [gorre03/AmazonReflinkLite#1]
ciao stavo provando il tuto script, ma ho notato che il bot non genera il link. dopo averlo cancellato appare il messaggio Link Amazon inviato da xxxxx, e si ferma

**Comment by gorre03** [comment]
Hai messo il token bitly?
Altrimenti non va.

**Comment by gorre03** [comment]
> ciao stavo provando il tuto script, ma ho notato che il bot non genera il link. dopo averlo cancellato appare il messaggio Link Amazon inviato da xxxxx, e si ferma
Hai messo il token bitly?
Altrimenti non va.

**Comment by ragnar-homekit** [comment]
Si sì l’ho messo ma nulla, non va

**Comment by gorre03** [comment]
> Si sì l’ho messo ma nulla, non va

Ho appena riprovato il bot e funziona. Puoi provare tu qui: t.me/GithubAmazonReflinkLiteBot. Leggi bene il README.md e la guida su come creare il token bitly. Il bot gestisce solo i link amazon.it che hanno un asin quindi sono escluse tutte le pagine.

**Comment by gorre03** [comment]
Leggi bene questo punto del <a href="https://github.com/gorre03/AmazonReflinkLite/blob/master/README.md#installazione">README</a>.

**Comment by ragnar-homekit** [comment]
ho seguito tutto perfettamente, a questo punto penso sia l'hosting altervista che non va bene

**Comment by gorre03** [comment]
> ho seguito tutto perfettamente, a questo punto penso sia l'hosting altervista che non va bene

Nono il bot va ovunque. Su altervista l'ho anche testato e funziona. Ovviamente tu non hai toccato il codice vero? Hai provato il bot che ti ho linkato qui sopra?

**Comment by ragnar-homekit** [comment]
ok allora non è altervista, non ho toccato il codice assolutamente, si ho provato il tuo bot e ho visto che funziona. non so che può essere allora, il token bitly a sto punto

**Comment by gorre03** [comment]
> ok allora non è altervista, non ho toccato il codice assolutamente, si ho provato il tuo bot e ho visto che funziona. non so che può essere allora, il token bitly a sto punto

Si sicuramente è il token bitly... Se vuoi mandarmelo starta il bot e invialo così ti dico se è valido o meno, poi lo revoki.

**Comment by ragnar-homekit** [comment]
![Schermata 2020-05-03 alle 14 13 02](https://user-images.githubusercontent.com/7750267/80913882-48659500-8d48-11ea-8376-a1b2273b6a77.png)
 tu il token lo generi da "Generic Access Token" come nello scree?

**Comment by gorre03** [comment]
> ![Schermata 2020-05-03 alle 14 13 02](https://user-images.githubusercontent.com/7750267/80913882-48659500-8d48-11ea-8376-a1b2273b6a77.png)
> tu il token lo generi da "Generic Access Token" come nello scree?

Si clicca su Generic Acces Token poi ti chiede la password e ti viene mostrato a schermo il token

**Comment by ragnar-homekit** [comment]
Eh allora non è neanche un problema del token, perché ho sempre messo quello.

**Comment by gorre03** [comment]
> Eh allora non è neanche un problema del token, perché ho sempre messo quello.

Ho rilasciato la nuova versione dell'index.php. Ora ti dovrebbe arrivare direttamente su tg l'errore.

**Comment by ragnar-homekit** [comment]
perfetto, ora lo provo subito e ti aggiorno

**Comment by gorre03** [comment]
Si, è bitly. Però non ho mai sentito quell'errore😂. Ti dice solo N? Allora fai così crea un'altro account bitly con un'altro indirizzo email e risolvi tutto

**Comment by ragnar-homekit** [comment]
si come errore da solo N, ho creato un nuovo account ma il problema rimane, stesso errore

**Comment by gorre03** [comment]
Mi dispiace, allora il tuo server sarà stato bannato da bitly. Quell'errore è inesistente. Online non si trova niente. Se sai un minimo di php riesci a risolvere bypassando bitly.

**Comment by gorre03** [comment]
Comunque ora chiudo l'issue e tra qualche giorno se ne hai bisogno rilascio un'aggiornamento senza bitly. Se hai altre domande commenta qui sotto.
